# -*- coding: utf-8 -*-
"""Automated_Ivanagita.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g840E438pA6tph-c2ibCLO1Yr5M8Q0UE
"""

import pandas as pd
from sklearn.preprocessing import StandardScaler

def run_automation(input_path, output_path):
    # Load data
    df = pd.read_csv(input_path)

    # --- PROSES PREPROCESSING ---
    df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
    df.dropna(inplace=True)
    df.drop_duplicates(inplace=True)

    if 'customerID' in df.columns:
        df.drop('customerID', axis=1, inplace=True)

    if 'Churn' in df.columns:
        df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})

    df = pd.get_dummies(df)

    scaler = StandardScaler()
    num_cols = ['tenure', 'MonthlyCharges', 'TotalCharges']
    df[num_cols] = scaler.fit_transform(df[num_cols])

    # Simpan hasil ke folder namadataset_preprocessing
    df.to_csv(output_path, index=False)
    print(f"Otomatisasi selesai! Data disimpan di: {output_path}")

if __name__ == "__main__":
    # Menjalankan fungsi
    run_automation('dataset_raw.csv', 'dataset_clean.csv')